"""
agents/report_agent.py
-----------------------
Report Agent — generates the final Markdown research report.

Responsibilities
----------------
• Accept outputs from all upstream agents.
• Produce a clean, well-formatted Markdown report.
• Save the report to the reports/ directory.
• Return the report as a string for display or download.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

# Reports are saved here (relative to project root)
_REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"


class ReportAgent:
    """
    Generates and saves the final stock research report in Markdown format.

    Usage
    -----
    agent  = ReportAgent()
    result = agent.run(data, financial, technical, sentiment, risk, decision)
    """

    DISCLAIMER = (
        "> **⚠️ EDUCATIONAL DISCLAIMER**: This report is generated by an automated "
        "AI research system for **educational and research purposes only**. It does "
        "**NOT** constitute financial advice, investment recommendations, or any form "
        "of professional guidance. Past performance is not indicative of future results. "
        "Always consult a qualified financial advisor before making investment decisions. "
        "The authors and developers of FinAgent accept no liability for any financial "
        "decisions made based on this report."
    )

    def __init__(self) -> None:
        self.name = "Report Agent"
        _REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def run(
        self,
        data: Dict[str, Any],
        financial: Dict[str, Any],
        technical: Dict[str, Any],
        sentiment: Dict[str, Any],
        risk: Dict[str, Any],
        decision: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Generate the full Markdown research report.

        Returns
        -------
        dict with keys:
            success      : bool
            error        : str | None
            report_text  : str   (full Markdown report)
            report_path  : str   (absolute path where report was saved)
            filename     : str
        """
        result: Dict[str, Any] = {
            "success": False,
            "error": None,
            "report_text": "",
            "report_path": "",
            "filename": "",
        }

        ticker: str = data.get("ticker", "UNKNOWN")
        company: str = data.get("company_name", ticker)
        logger.info("[%s] Generating report for %s", self.name, ticker)

        try:
            report_text = self._build_report(data, financial, technical, sentiment, risk, decision)
        except Exception as exc:
            logger.error("[%s] Failed to build report: %s", self.name, exc)
            result["error"] = f"Report generation failed: {exc}"
            return result

        # ── Save to disk ───────────────────────────────────────────────────
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{ticker}_{timestamp}.md"
        report_path = _REPORTS_DIR / filename

        try:
            with open(report_path, "w", encoding="utf-8") as f:
                f.write(report_text)
            logger.info("[%s] Report saved to %s", self.name, report_path)
        except OSError as exc:
            logger.warning("[%s] Could not save report: %s", self.name, exc)
            # Non-fatal — return the report text anyway

        result.update(
            {
                "success": True,
                "report_text": report_text,
                "report_path": str(report_path),
                "filename": filename,
            }
        )
        return result

    # ------------------------------------------------------------------
    # Private report builder
    # ------------------------------------------------------------------

    def _build_report(
        self,
        data: Dict[str, Any],
        financial: Dict[str, Any],
        technical: Dict[str, Any],
        sentiment: Dict[str, Any],
        risk: Dict[str, Any],
        decision: Dict[str, Any],
    ) -> str:
        """Compose the full Markdown report string."""

        ticker       = data.get("ticker", "N/A")
        company      = data.get("company_name", ticker)
        sector       = data.get("sector", "N/A")
        industry     = data.get("industry", "N/A")
        price        = data.get("current_price")
        price_str    = f"${price:.2f}" if price else "N/A"

        fin_score    = financial.get("financial_score", "N/A")
        fin_label    = financial.get("score_label", "N/A")
        tech_signal  = technical.get("signal", "N/A")
        news_sent    = sentiment.get("sentiment", "N/A")
        risk_level   = risk.get("risk_level", "N/A")
        risk_score   = risk.get("risk_score", "N/A")
        rec          = decision.get("recommendation", "N/A")
        conf         = decision.get("confidence", 0.0)

        rec_emoji    = {"Buy": "🟢", "Hold": "🟡", "Sell": "🔴"}.get(rec, "⚪")
        risk_emoji   = {"Low": "🟢", "Medium": "🟡", "High": "🔴"}.get(risk_level, "⚪")
        tech_emoji   = {"Bullish": "📈", "Neutral": "➡️", "Bearish": "📉"}.get(tech_signal, "")
        sent_emoji   = {"Positive": "😊", "Neutral": "😐", "Negative": "😟"}.get(news_sent, "")

        now = datetime.now().strftime("%B %d, %Y at %H:%M")
        metrics = financial.get("metrics", {})
        indicators = technical.get("indicators", {})
        risk_factors = risk.get("risk_factors", {})

        lines = [
            f"# 📊 FinAgent Stock Research Report",
            f"",
            self.DISCLAIMER,
            f"",
            f"---",
            f"",
            f"## 🏢 Company Overview",
            f"",
            f"| Field          | Value                    |",
            f"|----------------|--------------------------|",
            f"| **Ticker**     | `{ticker}`               |",
            f"| **Company**    | {company}                |",
            f"| **Sector**     | {sector}                 |",
            f"| **Industry**   | {industry}               |",
            f"| **Price**      | {price_str}              |",
            f"| **Report Date**| {now}                    |",
            f"",
            f"---",
            f"",
            f"## 💰 Financial Health Analysis",
            f"",
            f"**Score: {fin_score}/10 — {fin_label}**",
            f"",
            self._format_bullet_list(financial.get("reasons", [])),
            f"",
            f"### Key Metrics",
            f"",
            self._format_metrics_table(metrics),
            f"",
            f"---",
            f"",
            f"## 📈 Technical Analysis",
            f"",
            f"**Signal: {tech_emoji} {tech_signal}**",
            f"",
            self._format_bullet_list(technical.get("reasons", [])),
            f"",
            f"### Technical Indicators",
            f"",
            self._format_metrics_table(indicators),
            f"",
            f"---",
            f"",
            f"## 📰 News Sentiment Analysis",
            f"",
            f"**Sentiment: {sent_emoji} {news_sent}** "
            f"(score: {sentiment.get('sentiment_score', 0.0):+.3f}, "
            f"{sentiment.get('headline_count', 0)} headline(s) analysed)",
            f"",
            self._format_bullet_list(sentiment.get("reasons", [])),
            f"",
            f"---",
            f"",
            f"## ⚠️ Risk Analysis",
            f"",
            f"**Risk Level: {risk_emoji} {risk_level}** (score: {risk_score}/10)",
            f"",
            self._format_bullet_list(risk.get("reasons", [])),
            f"",
            f"### Risk Factor Breakdown",
            f"",
            self._format_metrics_table(risk_factors),
            f"",
            f"---",
            f"",
            f"## 🏁 Final Recommendation",
            f"",
            f"### {rec_emoji} {rec} — Confidence: {conf:.0f}%",
            f"",
            f"{decision.get('summary', '')}",
            f"",
        ]

        llm_summary = decision.get("llm_summary")
        if llm_summary:
            lines.extend([
                f"### 🤖 AI Analyst Summary",
                f"",
                f"> {llm_summary}",
                f"",
            ])

        lines.extend([
            f"**Decision Rationale:**",
            f"",
            self._format_bullet_list(decision.get("reasons", [])),
            f"",
            f"### Agent Signal Summary",
            f"",
            f"| Agent                      | Signal                        |",
            f"|----------------------------|-------------------------------|",
            f"| 💰 Financial Analysis       | {fin_score}/10 ({fin_label}) |",
            f"| 📈 Technical Analysis       | {tech_emoji} {tech_signal}   |",
            f"| 📰 News Sentiment           | {sent_emoji} {news_sent}     |",
            f"| ⚠️  Risk Assessment          | {risk_emoji} {risk_level}    |",
            f"| 🏁 **Final Decision**       | **{rec_emoji} {rec} ({conf:.0f}% confidence)** |",
            f"",
            f"---",
            f"",
            f"## 📚 Educational Notes",
            f"",
            f"| Term              | Plain-Language Explanation |",
            f"|-------------------|---------------------------|",
            f"| **P/E Ratio**     | Price-to-Earnings ratio. Shows how much investors pay per dollar of earnings. Higher = more expensive. |",
            f"| **RSI**           | Relative Strength Index. Momentum oscillator 0–100. >70 = overbought; <30 = oversold. |",
            f"| **Moving Average**| Average price over N days. Helps smooth noise and identify trends. |",
            f"| **Volatility**    | Annualised standard deviation of returns. Higher = bigger price swings. |",
            f"| **Debt-to-Equity**| Ratio of total debt to shareholders' equity. Higher = more leveraged. |",
            f"| **Beta**          | Sensitivity to market moves. Beta>1 = amplified swings vs the market. |",
            f"| **ROE**           | Return on Equity. How much profit per dollar of shareholders' equity. |",
            f"| **MACD**          | Moving Average Convergence Divergence. Trend-following momentum indicator. |",
            f"",
            f"---",
            f"",
            f"## ⚠️ Disclaimer",
            f"",
            self.DISCLAIMER,
            f"",
            f"---",
            f"",
            f"*Report generated by FinAgent v1.0 on {now}*",
            f"",
        ])

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Formatting helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _format_bullet_list(items: list) -> str:
        if not items:
            return "*No details available.*"
        return "\n".join(f"- {item}" for item in items)

    @staticmethod
    def _format_metrics_table(metrics: dict) -> str:
        if not metrics:
            return "*No metrics available.*"
        rows = ["| Metric | Value |", "|--------|-------|"]
        for k, v in metrics.items():
            rows.append(f"| {k} | {v} |")
        return "\n".join(rows)
